repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: debug-statements

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff
      args: [ --fix ]
      stages: [ pre-commit ]
    - id: ruff-format
      stages: [ pre-commit ]

default_language_version:
  python: python3.13
