# Generated by Django 5.1.7 on 2025-03-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("original_url", models.URLField(max_length=2083)),
                (
                    "short_code",
                    models.CharField(db_index=True, editable=False, max_length=12, unique=True),
                ),
            ],
            options={
                "verbose_name": "Shortened URL",
                "verbose_name_plural": "Shortened URLs",
            },
        ),
    ]
